/**@type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  "ReShade":           [{type: 'autogenerated', dirName: 'reshade'}],
  "Shaders":           [{type: 'autogenerated', dirName: 'shaders'}],
  "Additional Guides": [{type: 'autogenerated', dirName: 'additionalguides'}],
};

export default sidebars;
